version: 0.2

phases:
  pre_build:
    commands:
      - echo logging into docker
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - docker build -t $tag:latest .
      - docker tag $tag:latest $ecr:$tag
      - docker push $ecr
  post_build:
    commands:
      - echo Build Completed. Create image definition file...
      - printf '[{"name":"jinspark-lab","imageUri":"%s"}]' $ecr:$tag > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json